apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airlock-gateway

resources:
- certificate-airlock-ca.yaml
- valkey-password-secret.yaml
- redisprovider.yaml
- valkey-client-cert.yaml
- sessionHandling.yaml
