---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager
  - ca
  - valkey-sessionstore/overlays/k8s
  - logging-and-reporting/overlays/k8s
  - airlock-microgateway/overlays/k8s
  - nextcloud
  - juice-shop
  - podinfo
  - nextcloud-microgateway-config
  - juice-shop-microgateway-config
  - webserver
  - webserver-microgateway-config
