---
apiVersion: microgateway.airlock.com/v1alpha1
# RedisProvider is also used for Valkey-compatible session stores.
kind: RedisProvider
metadata:
  name: sessionagent
  namespace: nextcloud
spec:
  mode:
    standalone:
      host: valkey.valkey.svc.cluster.local
      port: 6379
  tls:
    certificateVerification:
      #disabled: {}
      custom:
        trustedCA:
          certificates:
          - secretRef:
              name: airlock-ca
    clientCertificate:
      secretRef:
        name: valkey-client-cert
  auth:
    password:
      secretRef:
        name: valkey-password
