apiVersion: v1
kind: Secret
metadata:
  name: lokistack-object-storage
type: Opaque
stringData:
  access_key_id: airlock
  access_key_secret: Start123!
  bucketnames: loki
  endpoint: http://rustfs.monitoring.svc.cluster.local:9000
  forcepathstyle: "true"
  region: us-east-1
