apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: crc-csi-hostpath-provisioner
