apiVersion: v1
kind: Service
metadata:
  name: rustfs
spec:
  ports:
  - name: api
    port: 9000
    targetPort: api
  - name: console
    port: 9001
    targetPort: console
  selector:
    app.kubernetes.io/name: rustfs
