---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trace-demo

resources:
  - namespace.yaml
  - configmap_block.yaml
  - customresponse.yaml
  - customresponsepolicy.yaml

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: 6.14.1
    releaseName: podinfo
    valuesFile: values.yaml
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: 6.14.1
    releaseName: podinfo-slow
    valuesFile: values-slow.yaml

patches:
  - target:
      kind: Pod
      annotationSelector: "helm.sh/hook=test-success"
    patch: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: not-used
      $patch: delete
