apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valkey-certificate
  namespace: valkey
spec:
  dnsNames:
  - valkey.valkey.svc.cluster.local

  privateKey:
    size: 4096

  usages:
  - client auth
  - server auth

  commonName: valkey.valkey.svc.cluster.local

  issuerRef:
    kind: ClusterIssuer
    name: cluster-ca-issuer

  secretName: valkey-certificate
